# Base Image with Bun pre-installed

FROM oven/bun

# Set the working directory 
WORKDIR /app

# Copy the Source Code
COPY . /app/

# Install dependencies
RUN bun install

# Start the Application
CMD ["bun", "run", "start"]